### ISSUE TITLE
Possible bug in this library

### ISSUE THREAD

**Issue by henrikra** [kogai/typed_i18n#8] opened 2018-07-10 13:41 UTC
I wrote down full details of this bug in here https://github.com/Microsoft/vscode/issues/53962 because I suspect that the bug is in the editor. What editor you use @kogai ?

**Comment by kogai** [comment] 2018-07-11 02:42
I'm usually using `vscode` but also use `flow` instead of `typescript` and as far as I know, the language server of `flow` can't suggest completion from such a literal type.

So, I agree with your expectations which those behavior is caused by `vscode`, I guess that it is caused by the language server of `typescript` which works inside `vscode`.

**Comment by henrikra** [comment] 2018-07-11 05:56
Okay lets see when they answer. You have created great tool btw! I was looking for something that makes sure that my language strings are right and autocomplete would be nice too :)

**Comment by kogai** [comment] 2018-07-11 23:14
Ya, that's reasonable.
I'll update README soon. Thank you for your feedback!

**Comment by kogai** [comment] 2018-07-13 07:58
The vscode team said such behavior is a responsibility of vscode.
https://github.com/Microsoft/vscode/issues/53962#issuecomment-404077908

Therefore I'll close this Issue when #9 which modify README has been merged.

**Closed** 2018-07-13 08:39 UTC
